name: Extension Test and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Debug BackgroundSpec
      run: cat /home/runner/work/puppet/puppet/earth/Tests/BackgroundSpec.js

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Change to your preferred Node.js version
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Clear Yarn cache
      run: yarn cache clean
      
    - name: Install dependencies
      run: npm install

    - name: Run Jasmine tests
      run: npm install --save-dev jasmine
    
    - name: Configure Jasmine 
      run: npm install -g jasmine
    
    - name: Install jasmine-ajax
      run: npm install jasmine-ajax --save-dev
    
    - name: Configure project 
      run: npx jasmine init
    
    - name: Test project 
      run: npx jasmine /home/runner/work/puppet/puppet/earth/Tests/BackgroundSpec.js

  release:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Archive extension as a zip file
      run: |
        # Create a zip file of your extension or project
        zip -r extension.zip /home/runner/work/puppet/puppet/earth/Tests

    - name: Upload extension zip
      uses: actions/upload-artifact@v2
      with:
        name: extension-zip
        path: extension.zip
