name: Zip Extension File

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository code

    - name: Zip Extension File
      run: |
        # Navigate to the directory containing your extension files
        cd home/runner/work/puppet/earth/
        # Zip the extension file(s)
        zip -r extension.zip .

    - name: Upload Zip File
      uses: actions/upload-artifact@v2
      with:
        name: extension  # Replace with a suitable artifact name
        path: /home/runner/work/puppet/earth
